#!/bin/sh

#
#  Copyright (c) 2024 Original Author(s), PhonePe India Pvt. Ltd.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

chown root:root /etc/init/drove-controller.conf
chown root:root /etc/init.d/drove-controller
chown root:root /usr/share/java/drove-controller.jar
chown root:root /usr/lib/systemd/system/drove-controller.service
chown root:root /usr/bin/drove-controller

# SystemD
if which systemctl >/dev/null; then
    echo "Registering SystemD service: drove-controller"
    systemctl daemon-reload
    systemctl enable "drove-controller"
    systemctl start "drove-controller"
    exit 0
fi

# Upstart
if which initctl >/dev/null; then
    echo "Registering Upstart service: drove-controller"
    initctl reload-configuration
    initctl start "drove-controller"
    exit 0
fi

# SystemV
if which invoke-rc.d >/dev/null; then
    echo "Registering SystemV service: drove-controller"
    update-rc.d "drove-controller" defaults
    invoke-rc.d "drove-controller" start
    exit 0
fi

echo "Unable to find supported init system."
exit 1
