#!/bin/sh -e

#
#  Copyright (c) 2024 Original Author(s), PhonePe India Pvt. Ltd.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

case "$1" in
    install|upgrade)
        if ! getent passwd "drove" >/dev/null; then
            adduser --system --group "drove" --home /var/lib/misc --no-create-home > /dev/null
        fi

        mkdir -p "/var/log/drove/drove-controller" && chown -R "drove:drove" "/var/log/drove/drove-controller"
    ;;

esac

exit 0
