#!/bin/sh

#
#  Copyright (c) 2024 Original Author(s), PhonePe India Pvt. Ltd.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

# SystemD
if which systemctl >/dev/null; then
    echo "Removing SystemD service: drove-controller"
    systemctl stop "drove-controller"
    systemctl disable "drove-controller"
    systemctl daemon-reload
    exit 0
fi

# Upstart
if which initctl >/dev/null; then
    echo "Removing Upstart service: drove-controller"
    initctl stop "drove-controller"
    initctl reload-configuration
    exit 0
fi

# SystemV
if which invoke-rc.d >/dev/null; then
    echo "Removing SystemV service: drove-controller"
    invoke-rc.d "drove-controller" stop
    update-rc.d "drove-controller" remove
    exit 0
fi

echo "Unable to find supported init system."
exit 1
