#!/bin/bash

#
#  Copyright (c) 2024 Original Author(s), PhonePe India Pvt. Ltd.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

### BEGIN INIT INFO
# Provides:             drove-executor
# Required-Start:
# Required-Stop:
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    drove-executor
### END INIT INFO

. /lib/lsb/init-functions

PID_FILE="/var/run/drove-executor.pid"

do_start() {
    start-stop-daemon --start --quiet --pidfile "${PID_FILE}" --exec "/usr/bin/drove-executor" --test > /dev/null || return 1
    start-stop-daemon --start --quiet --pidfile "${PID_FILE}" --chuid "drove:drove" --exec "/usr/bin/drove-executor" --make-pidfile --background --name "drove-executor" || return 2
    return 0
}

do_stop() {
    start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile "${PID_FILE}" --name "drove-executor"
    RETVAL="$?"
    [ "${RETVAL}" = 2 ] && return 2
    rm -f "${PID_FILE}"
    return "${RETVAL}"
}

case "$1" in
    start)
        do_start
        exit $?
        ;;
    stop)
        do_stop
        exit $?
        ;;
    status)
        status_of_proc -p "${PID_FILE}" "/usr/bin/drove-executor" "drove-executor"
        exit $?
        ;;
    restart|reload)
        do_stop
        do_start
        exit $?
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac

exit 0
