#!/bin/sh

chown root:root /etc/init/drove-executor.conf
chown root:root /etc/init.d/drove-executor
chown root:root /usr/share/java/drove-executor.jar
chown root:root /usr/lib/systemd/system/drove-executor.service
chown root:root /usr/bin/drove-executor

# SystemD
if which systemctl >/dev/null; then
    echo "Registering SystemD service: drove-executor"
    systemctl daemon-reload
    systemctl enable "drove-executor"
    systemctl start "drove-executor"
    exit 0
fi

# Upstart
if which initctl >/dev/null; then
    echo "Registering Upstart service: drove-executor"
    initctl reload-configuration
    initctl start "drove-executor"
    exit 0
fi

# SystemV
if which invoke-rc.d >/dev/null; then
    echo "Registering SystemV service: drove-executor"
    update-rc.d "drove-executor" defaults
    invoke-rc.d "drove-executor" start
    exit 0
fi

echo "Unable to find supported init system."
exit 1
