#!/bin/sh -e

case "$1" in
    install|upgrade)
        if ! getent passwd "drove" >/dev/null; then
            adduser --system --group "drove" --home /var/lib/misc --no-create-home > /dev/null
            usermod -aG docker drove
        fi

        mkdir -p "/var/log/drove/drove-executor" && chown -R "drove:drove" "/var/log/drove/drove-executor"
    ;;

esac

exit 0
